[package]
name = "blob_guy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true # Not having that causes wine debugger to crash.
panic = "abort"
split-debuginfo = "packed"
incremental=true
codegen-units=1
opt-level = 3

[dependencies]
noita_api = {path = "../noita_api"}
eyre = "0.6.12"
libloading = "0.8.8"
smallvec = "1.15.1"
rustc-hash = "2.1.1"